title: Apostila de Desenvolvimento Web
description: Curso Técnico em Multimídia — CEET Vasco Coutinho
theme: just-the-docs

# Ativa a busca
search_enabled: true

# Cor de destaque (opcional)
color_scheme: light
