title: Desenvolvimento Web
description: Material didatico da disciplina de Desenvolvimento Web - Curso Tecnico em Multimidia - CEET Vasco Coutinho
baseurl: "/desenvolvimento-web"
url: "https://rafaelacorrea81.github.io"
theme: just-the-docs
color_scheme: light
search_enabled: true
nav_sort: case_insensitive

aux_links:
  "Repositorio no GitHub":
    - "https://github.com/rafaelacorrea81/desenvolvimento-web"

back_to_top: true
back_to_top_text: "Voltar ao topo"

footer_content: "Disciplina de Desenvolvimento Web - Curso Tecnico em Multimidia - CEET Vasco Coutinho"

exclude:
  - SUMMARY.md
  - README.md
  - Gemfile
  - Gemfile.lock
